name: FinPay-Payment SDK Release

on:
  push:
    tags:
      - 'v*'

jobs:
  start:
    name: Start Deploy Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 📥
        uses: actions/checkout@v3

      - name: Cache JDK and Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/jdk
          key: ${{ runner.os }}-jdk-gradle-${{ hashFiles('**/*.gradle*', '**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17 📦
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew 📜
        run: chmod +x gradlew

      - name: Ping Slack Test & Deploy Android AAR Started
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: Test & Deploy AAR Started

#  workflow-lint:
#    uses: ./.github/workflows/work-call-ci-lint.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'core_module'
#
#  workflow-test-unit:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/work-call-ci-test-unit.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'core_module'
#
#  workflow-test-android:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/work-call-ci-test-android.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'core_module'

  workflow-assemble-aar:
    uses: ./.github/workflows/work-call-ci-assemble-aar.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      MODULE_NAME: 'core_module'

  workflow-sing-aar:
    needs: [ workflow-assemble-aar ]
    uses: ./.github/workflows/work-call-cd-sign-arr.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      UPLOADED_FILES_ID: 'assemble_module'
      UPLOADED_ZIP_ID: 'zip_module'
      MODULE_NAME: 'core_module'


  workflow-git_release_upload_files:
    needs: [ workflow-sing-aar ]
    uses: ./.github/workflows/work-call-cd-git-release-module.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      UPLOADED_FILES_ID: 'zip_module'
      DOWNLOAD_FILE_URL: ${{needs.workflow-sing-aar.outputs.release_url}}


#  finish:
#    needs: [ workflow-git_release_upload_files ]
#    name: Finish Deploy Workflow
#    runs-on: ubuntu-latest
#    steps:
#      - name: Ping Slack Test & Deploy AAR Finished Successfully
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: success()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: |
#            *A New release AAR Uploaded Successfully*
#            ${{ needs.workflow-git_release_upload_files.outputs.release_url }}
#          color: success
#
#      - name: Ping Slack Test & Deploy Android AAR Failed
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: failure()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: |
#            *A new Release failed*
#          color: failure
