name: FinPay-Payment SDK Release

on:
  push:
    tags:
      - 'v*'

jobs:
  start:
    name: Start Deploy Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Ping Slack Test & Deploy Android AAR Started
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: Test & Deploy AAR Started

#  workflow-lint:
#    uses: ./.github/workflows/work-call-ci-lint.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'app'
#
#  workflow-test-unit:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/work-call-ci-test-unit.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'app'
#
#  workflow-test-android:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/work-call-ci-test-android.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'app'

  workflow-assemble-aar:
    uses: ./.github/workflows/work-call-ci-assemble-bundle.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      MODULE_NAME: 'app'

  workflow-sing-aar:
    needs: [ workflow-assemble-aar ]
    uses: ./.github/workflows/work-call-cd-sign-arr.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_STORE_FILE_CONTENT: ${{ secrets.KEY_STORE_FILE }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    with:
      UPLOADED_ARR_FILES_ID: ${{needs.workflow-assemble-aar.outputs.arr_folder_id}}
      MODULE_NAME: 'app'


  workflow-git_release_upload_files:
    needs: [ workflow-sing-aar ]
    uses: ./.github/workflows/work-call-cd-git-release-module.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      UPLOADED_ZIP_FOLDER_ID: ${{needs.workflow-sing-aar.outputs.zip_folder_id}}
      DOWNLOAD_FILE_URL: ${{needs.workflow-sing-aar.outputs.release_url}}

  finish:
    needs: [ workflow-git_release_upload_files ]
    name: Finish Deploy Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Ping Slack Test & Deploy AAR Finished Successfully
        uses: someimportantcompany/github-actions-slack-message@v1
        if: success()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            *A New release AAR Uploaded Successfully*
            ${{ needs.workflow-git_release_upload_files.outputs.release_url }}
          color: success

      - name: Ping Slack Test & Deploy Android AAR Failed
        uses: someimportantcompany/github-actions-slack-message@v1
        if: failure()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            *A new Release failed*
          color: failure
