name: core_module Module Release

on:
  push:
    tags:
      - 'v*'

jobs:
  start:
    name: Start Deploy Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Ping Slack Test & Deploy Android AAR Started
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: Test & Deploy AAR Started

#  workflow-lint:
#    uses: ./.github/workflows/work-call-ci-lint.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'core_module'

#  workflow-test-unit:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/work-call-ci-test-unit.yml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      MODULE_NAME: 'core_module'

  workflow-test-android:
    uses: ./.github/workflows/work-call-ci-test-android.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      MODULE_NAME: 'core_module'

  workflow-assemble-aar:
    needs: [ workflow-test-unit, workflow-test-android ]
    uses: ./.github/workflows/work-call-ci-assemble-aar.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      MODULE_NAME: 'core_module'

  workflow-rename-aar:
    needs: [ workflow-assemble-aar ]
    uses: ./.github/workflows/work-call-cd-rename-aar.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      UPLOADED_ARR_FILES_ID: ${{needs.workflow-assemble-aar.outputs.arr_folder_id}}
      MODULE_NAME: 'core_module'

  workflow-git_release_upload_files:
    needs: [ workflow-rename-aar ]
    uses: ./.github/workflows/work-call-cd-git-release-module.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      UPLOADED_FILES_ID: ${{needs.workflow-rename-aar.outputs.aar_folder_id}}

  finish:
    needs: [ workflow-git_release_upload_files ]
    name: Finish Deploy Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Ping Slack Test & Deploy AAR Finished Successfully
        uses: someimportantcompany/github-actions-slack-message@v1
        if: success()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            *A New release AAR Uploaded Successfully*
            ${{ needs.workflow-git_release_upload_files.outputs.release_url }}
          color: success

      - name: Ping Slack Test & Deploy Android AAR Failed
        uses: someimportantcompany/github-actions-slack-message@v1
        if: failure()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            *A new Release failed*
          color: failure
