name: Android Emulator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'android-31'

      - name: Create Emulator
        run: |
          echo no | avdmanager create avd --force --name test_emulator --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'

      - name: Start Emulator
        run: |
          emulator -avd test_emulator -no-snapshot -no-window -no-audio &

      - name: Wait for Emulator
        run: |
          |
          # Check if the emulator is running
          is_running=false
          while [ "$is_running" == "false" ]; do
            if adb devices | grep "emulator-5554" &> /dev/null; then
              echo "Emulator is running."
              is_running=true
            else
              echo "Emulator is not running yet. Waiting..."
              sleep 5
            fi
          done

      - name: Build and Test
        run: |
          ./gradlew build connectedCheck