name: Run Android Lint

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
    inputs:
      MODULE_NAME:
        description: 'Which module you need to run this flow on...'
        type: string
        required: true

jobs:
  lint:
    name: Run Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache OWASP Dependency-Check data
        id: cache-owasp
        uses: actions/cache@v3
        with:
          path: |
            ~/.ossindex
            ~/.cache/dependency-check
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-

      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.2.0/dependency-check-9.2.0-release.zip
          unzip dependency-check-9.2.0-release.zip

      - name: Run OWASP Dependency-Check for MyProject
        run: |
          ./dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --format "ALL" --out ./dependency-check-report

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report
