name: Run Android Lint

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
    inputs:
      MODULE_NAME:
        description: 'Which module you need to run this flow on...'
        type: string
        required: true

jobs:
  lint:
    name: Run Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Run Dependency-Check
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - run: |
          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.2.2-release.zip
          unzip dependency-check-6.2.2-release.zip
          ./dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --format "ALL" --out ./dependency-check-report
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: ./dependency-check-report
#      - name: Run Lint
#        run: ./gradlew ${{ inputs.MODULE_NAME }}:lint
#
#      - name: Upload html test report
#        # Upload report to ubuntu server to be used on another action...
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint_report
#          path: ${{ inputs.MODULE_NAME }}/build/reports/lint-results-*

#      - name: Ping Slack Android Lint Failed
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: failure()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: |
#            *Android Lint failed*
#          color: failure
